<?php
/**
 * @file
 * .module file for rnd15_site_wysiwyg_styles module
 *
 * This module is used to configure the ckeditor with our style-guide and bespoke buttons.
 *
 * @author Carl Hinton for Comic Relief.
 */

/**
 * Implements hook_ckeditor_settings_alter.
 *
 * @param $settings
 * @param $conf
 */
function rnd15_site_wysiwyg_styles_ckeditor_settings_alter(&$settings, $conf) {

    // Override the default styles drop-down list, replace with ours from style-guide.
    $url = drupal_get_path('module', 'rnd15_site_wysiwyg_styles');
    $settings['stylesCombo_stylesSet'] = 'drupal:/' . $url . '/ckeditor.styles.js';

    // This section adds our button plugins.
    $buttons = rnd15_site_wysiwyg_styles_plugin_definitions();
    // This fix is needed as there is an inconsistancy in the ckeditor module.
    foreach($buttons as $key => $button) {
        $buttons[$key]['path'] = '/' . $buttons[$key]['path'];
    }
    $existing = $settings['loadPlugins'];
    $settings['loadPlugins'] = array_merge($buttons, $existing);
    $docs = variable_get('ckeditor_documentation',
        'http://jira.comicrelief.com:8090/pages/viewpage.action?title=WYSIWYG+Editor&spaceKey=rnd15Documentation');
    drupal_add_js(array('rnd15_site_wysiwyg_styles' => array('docs' => $docs)), 'setting');
}

/**
 * Implements hook_ckeditor_plugin.
 *
 * This adds our button plugins to the ckeditor config page.
 * @return array
 */
function rnd15_site_wysiwyg_styles_ckeditor_plugin() {

   return rnd15_site_wysiwyg_styles_plugin_definitions();

}

/**
 * Helper, so that we only define our plugins once.
 * @return array
 */
function rnd15_site_wysiwyg_styles_plugin_definitions() {

    $plugins = array();

 /*
  * RND Buttons Plugin Configuration
  */

    $plugins['rndButtons'] = array(
            // Name of the plugin used to write it.
            'name' => 'rndButtons',
            // Description of the plugin - it would be displayed in the plugins management section of profile settings.
            'desc' => t('Insert a RND button'),
            // The full path to the CKEditor plugins directory, with the trailing slash.
            'path' => drupal_get_path('module', 'rnd15_site_wysiwyg_styles') . '/plugins/rndButtons/',
            'default' => 't',
            'buttons' => array(
                'rndButtons' => array(
                    'icon' => 'rndButtons.png',
                    'label' => 'RND button',
                )
            )
        );

/*
 * RND Ghost Buttons Plugin Configuration
 */

    $plugins['rndButtonsGhost'] = array(
        // Name of the plugin used to write it.
        'name' => 'rndButtonsGhost',
        // Description of the plugin - it would be displayed in the plugins management section of profile settings.
        'desc' => t('Insert a RND ghost button'),
        // The full path to the CKEditor plugins directory, with the trailing slash.
        'path' => drupal_get_path('module', 'rnd15_site_wysiwyg_styles') . '/plugins/rndButtonsGhost/',
        'default' => 't',
        'buttons' => array(
            'rndButtonsGhost' => array(
                'icon' => 'rndButtonsGhost.png',
                'label' => 'RND Ghost button',
            )
        )
    );

 /*
  * RND Links Plugin Configuration
  */

    $plugins['rndLinks'] = array(
        // Name of the plugin used to write it.
        'name' => 'rndLinks',
        // Description of the plugin - it would be displayed in the plugins management section of profile settings.
        'desc' => t('Insert a RND link'),
        // The full path to the CKEditor plugins directory, with the trailing slash.
        'path' => drupal_get_path('module', 'rnd15_site_wysiwyg_styles') . '/plugins/rndLinks/',
        'default' => 't',
        'buttons' => array(
            'rndLinks' => array(
                'icon' => 'rndLinks.png',
                'label' => 'RND Link',
            )
        )
    );

 /*
  * RND Bullets Plugin Configuration
  */

    $plugins['rndBullets'] = array(
        // Name of the plugin used to write it.
        'name' => 'rndBullets',
        // Description of the plugin - it would be displayed in the plugins management section of profile settings.
        'desc' => t('Insert an RND bullet'),
        // The full path to the CKEditor plugins directory, with the trailing slash.
        'path' => drupal_get_path('module', 'rnd15_site_wysiwyg_styles') . '/plugins/rndBullets/',
        'default' => 't',
        'buttons' => array(
            'rndBullets' => array(
                'icon' => 'rndBullets.png',
                'label' => 'RND Bullet',
            )
        )
    );

    return $plugins;
}
