<?php
/**
 * @file
 */

/**
 * Implements hook_library
 *
 * Register the interstitial library
 */
function rnd15_site_interstitial_library() {
  $libraries['interstitial'] = array(
    'title' => 'Interstitial',
    'version' => '1.0',
    'js' => array(
      libraries_get_path('interstitial') . '/interstitial.jquery.min.js' => array(),
      libraries_get_path('interstitial') . '/interstitial.ageCheck.jquery.min.js' => array(),
    ),
    'version callback' => 'interstitial_version_callback',
  );
  return $libraries;
}

/**
 * Short-circuit the version argument.
 */
function interstitial_version_callback() { 
  return TRUE;
}

/**
 * Implements hook_preprocess_page
 *
 * Add the interstitial library to every page
 */
function rnd15_site_interstitial_preprocess_page($vars) {
  drupal_add_library('rnd15_site_interstitial', 'interstitial');
}

/**
 * Alter the list of menu item attributes.
 *
 * @param $attributes
 *   An array of attributes to be controlled by Menu Attributes, keyed by
 *   attribute name. Each attribute record should be an array with the following
 *   key/value pairs:
 *   - label: The human-readable name of the attribute.
 *   - description: The attribute description.
 *   - form: A Form API array. Some default values for this array are provided
 *     in menu_attributes_get_menu_attribute_info().
 *
 * @see menu_attributes_menu_attribute_info()
 * @see menu_attributes_get_menu_attribute_info()
 */
function rnd15_site_interstitial_menu_attribute_info() {
  // Add a Tabindex attribute.
  $info['data-interstitial'] = array(
    'label' => t('Interstitial Message'),
    'description' => t('Specify an interstitial message for a timed redirect. Wrap number in a &lt;i class="seconds"&gt; to have it count down. Due to height this is restricted to 320 characters including HTML.'),
    'form' => array(
      '#type' => 'textarea',
      '#resizable' => false,
      '#rows' => 2,
      '#maxlength' => 320,
    ),
  );
  $info['data-interstitial-delay'] = array(
    'label' => t('Interstitial Delay'),
    'description' => t('Specifies the delay in MS <em>For example: 5000 for 5 seconds.</em>'),
    'form' => array(
      '#maxlength' => 5,
      '#size' => 3,
    ),
  );
  return $info;
}